### ISSUE TITLE
More than one dll patches

### ISSUE THREAD

**Issue by mfr-fauzirahman** [ui3TD/IM-HarmonyIntegration#1] opened 2023-12-01 14:45 UTC
I assume this isn't possible with the current release, because I tried using string arrays in _**info.json**_ files like tags does but still failed, could you please implement it?

What I wanna do is creating a mod that implements some other mods without decompiling them (if you are Tel on Steam, I would like to also ask your permission), mainly TraitsFix, TraitsExpansion, and MBTI mod because currently I made a personal mod (idk if I ever release it to the public tho) that utilize those mods but needs to change the updated traits description in its respective JSON files.

Thank you for your time and effort.

**Comment by ui3TD** [comment] 2023-12-01 14:53
Yes, it does not take string arrays. Unfortunately I don't have so much time to add new features at the moment, but I'll take pull requests of course.
I highly suspect there's a suitable workaround. For example, if you just need to to change something in the JSON then you can do so with an offline duplicate of the mod.

**Closed as completed by ui3TD** 2023-12-01 14:53 UTC

**Comment by mfr-fauzirahman** [comment] 2023-12-01 15:13
I see, no problem then, I am willing to explore ways to rebuilding the source with the solution of this but so far no avail (and it already take few hours for that and a simple mod) and my free time is running out for now. 
The reason I add this issue is I figured if I ask here it could be faster since I am not touching any programming the last few years.

For the offline duplicate, yes I actually gonna do that for now, this issue was made because I have a plan to either release it or collaborate with someone, even though for now it will completely for my personal playthrough. If I would really release/collaborate it, decompiling mods so it uses one dll would not do justice to the creators for me.

Anyway, thanks for the really fast response and this great tool, made me played the game again since it would open some significant hope for the game's long run. Cheers, have a nice day.
